### ISSUE TITLE
Not working for me on windows.

### ISSUE THREAD

**Issue by rgkirch** [HumbleUI/HumbleUI#1]
I'm using clj installed in windows powershell. If I start a repl from cider in emacs and eval `make` then I get an error. 
e.g.
```clojure
(make
 {:on-close         (fn [])
  :on-screen-change (fn [])
  :on-resize        (fn [{:keys [window-width window-height content-width content-height]}])
  :on-frame         (fn [])
  :on-paint         (fn [canvas])
  :on-event         (fn [event])})
```

```
  Show: Project-Only All 
  Hide: Clojure Java REPL Tooling Duplicates  (16 frames hidden)

2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling c:/Users/richie/notMyCode/HumbleUI/HumbleUI/src/io/github/humbleui/window.clj at (107:1)
   #:clojure.error{:phase :compile-syntax-check,
                   :line 107,
                   :column 1,
                   :source
                   "c:/Users/richie/notMyCode/HumbleUI/HumbleUI/src/io/github/humbleui/window.clj"}
             Compiler.java: 7652  clojure.lang.Compiler/load
                      REPL:    1  user/eval8225
                      REPL:    1  user/eval8225
             Compiler.java: 7181  clojure.lang.Compiler/eval
             Compiler.java: 7136  clojure.lang.Compiler/eval
                  core.clj: 3202  clojure.core/eval
                  core.clj: 3198  clojure.core/eval
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 1977  clojure.core/with-bindings*
                  core.clj: 1977  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj:  662  clojure.core/apply
                regrow.clj:   20  refactor-nrepl.ns.slam.hound.regrow/wrap-clojure-repl/fn
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  152  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  202  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  201  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  831  java.lang.Thread/run

1. Caused by java.lang.UnsatisfiedLinkError
   'long io.github.humbleui.jwm.WindowWin32._nMake()'

          WindowWin32.java:   -2  io.github.humbleui.jwm.WindowWin32/_nMake
          WindowWin32.java:   14  io.github.humbleui.jwm.WindowWin32/<init>
                  App.java:   43  io.github.humbleui.jwm.App/makeWindow
                window.clj:   22  io.github.humbleui.window/make
                window.clj:   14  io.github.humbleui.window/make
                window.clj:  107  io.github.humbleui.window/eval8338
                window.clj:  107  io.github.humbleui.window/eval8338
             Compiler.java: 7181  clojure.lang.Compiler/eval
             Compiler.java: 7640  clojure.lang.Compiler/load
                      REPL:    1  user/eval8225
                      REPL:    1  user/eval8225
             Compiler.java: 7181  clojure.lang.Compiler/eval
             Compiler.java: 7136  clojure.lang.Compiler/eval
                  core.clj: 3202  clojure.core/eval
                  core.clj: 3198  clojure.core/eval
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 1977  clojure.core/with-bindings*
                  core.clj: 1977  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj:  662  clojure.core/apply
                regrow.clj:   20  refactor-nrepl.ns.slam.hound.regrow/wrap-clojure-repl/fn
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  152  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  202  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  201  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  831  java.lang.Thread/run
```
Also, if I run `.\script\run.py` I get an error saying... well, I'm not sure what.
```
PS C:\Users\richie\notMyCode\HumbleUI\HumbleUI> clojure
Clojure 1.11.0-alpha2
user=>
PS C:\Users\richie\notMyCode\HumbleUI\HumbleUI> clj
Clojure 1.11.0-alpha2
user=>
PS C:\Users\richie\notMyCode\HumbleUI\HumbleUI> .\script\run.py
Traceback (most recent call last):
  File "C:\Users\richie\notMyCode\HumbleUI\HumbleUI\script\run.py", line 15, in <module>
    sys.exit(main())
  File "C:\Users\richie\notMyCode\HumbleUI\HumbleUI\script\run.py", line 8, in main
    subprocess.check_call(["clojure",
  File "C:\Python39\lib\subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
I'm on windows 10. I followed [these](https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows) instructions to install clojure.
Thanks!

**Comment by tonsky** [comment]
The first error is probably because you haven’t called `(App/init)` first.
The second one (with the script) is unclear to me too, but I have seen it today. I’ve heard clj command line is not great on Windows, I’ll see what can be done

**Comment by rgkirch** [comment]
Thanks. Sorry I overlooked the `user.clj` file.

**Comment by peteruhnak** [comment]
> I'm on windows 10. I followed these instructions to install clojure.

Clojure on Windows (via the linked instructions) is only available as a PowerShell module, not as a system command in PATH, which means it will never be found. In principle, it is possible to invoke it as a `subprocess.check_call(['powershell', '-command', 'clojure', ...])`, however that will also require setting PS' execution policy to unrestricted (or maybe the module would have to be digitally signed).

Alternatively, you can create a `script/run.ps1` with the following content. (though both extensions starting with `p` is meh)

```
clojure -A:windows:dev -M -m user --interactive
```

unified entry points are always a pain so everyone ends up with `x` (or `x.sh`), `x.bat`, (and sometimes `x.ps1`)

**Comment by tonsky** [comment]
I removed dependency on `clj`, should invoke `java` directly now.

> unified entry points are always a pain

They worked pretty great for me so far both in https://github.com/HumbleUI/JWM and https://github.com/HumbleUI/Skija. I guess the solution is to ignore `clj` 🤷‍♂️

**Comment by rgkirch** [comment]
Thanks! Yea, it's working for me now.

**Comment by borkdude** [comment]
Just FYI, a bit late too the party.

Note that deps.clj works on Windows the same as it does on other OSes (macOS, linux):

https://github.com/borkdude/deps.clj

It is also available as `bb clojure` in babaska: it's a drop in replacement for the clojure CLI.

**Comment by tonsky** [comment]
@borkdude you are a saint! This should be a default, not the sh-based version!
