### ISSUE TITLE
`tools.namespace` dependency isn't available from clojars

### ISSUE THREAD

**Issue by jakeisnt** [HumbleUI/HumbleUI#57]
https://repo.clojars.org/org/clojure/tools.namespace/1.3.0/tools.namespace-1.3.0.jar link is dead: currently shows
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
org/clojure/tools.namespace/1.3.0/tools.namespace-1.3.0.jar
</Key>
<RequestId>6778X9N6YHYJA636</RequestId>
<HostId>
YeFF8pUj12TGQPZdYreSzK3F5rZmHDAsbj+bylqo6gKmbnLkcrmcqvhJfQ8Kw8hIi5o/t0bXKL+lJSYbtL74tQ==
</HostId>
</Error>
```

Trace running `nrepl.py`:
``` sh
[nix-shell:~/HumbleUI]$ ./script/nrepl.py
Downloading https://repo1.maven.org/maven2/io/github/humbleui/types/0.1.2/types-0.1.2-clojure.jar
Downloading https://repo1.maven.org/maven2/io/github/humbleui/jwm/0.4.10/jwm-0.4.10.jar
Downloading https://repo1.maven.org/maven2/io/github/humbleui/skija-shared/0.106.0/skija-shared-0.106.0.jar
Downloading https://repo1.maven.org/maven2/io/github/humbleui/skija-linux/0.106.0/skija-linux-0.106.0.jar
Downloading https://repo.clojars.org/nrepl/nrepl/1.0.0/nrepl-1.0.0.jar
Downloading https://repo.clojars.org/org/clojure/tools.namespace/1.3.0/tools.namespace-1.3.0.jar
Traceback (most recent call last):
  File "/home/jake/HumbleUI/./script/nrepl.py", line 20, in <module>
    sys.exit(main())
  File "/home/jake/HumbleUI/./script/nrepl.py", line 9, in main
    build_utils.fetch_maven("org.clojure", "tools.namespace", "1.3.0", repo = common.clojars),
  File "/home/jake/HumbleUI/script/build_utils.py", line 91, in fetch_maven
    fetch(repo + '/' + path, file)
  File "/home/jake/HumbleUI/script/build_utils.py", line 82, in fetch
    data = urllib.request.urlopen(url).read()
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by jakeisnt** [comment]
Looks like there are lots of forks available - but none directly provided by `clojure` - https://clojars.org/search?q=tools.namespace

**Comment by lilactown** [comment]
I believe tools.namespace is also available on maven central. I wonder why it's trying to download it from clojars?

**Comment by jakeisnt** [comment]
Clojars is hardcoded in the python script here:

https://github.com/HumbleUI/HumbleUI/blob/9a1f239b85d5913c2f386e8a2ef0d3f4c0760552/script/nrepl.py#L9

Looks easily fixable, but wasn't sure if this decision was deliberate

**Comment by tonsky** [comment]
Thanks! I guess they decided to finally nuke it from clojars
