### ISSUE TITLE
nrepl init fails on Windows 10

### ISSUE THREAD

**Issue by Dimagog** [HumbleUI/HumbleUI#63]
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045
```
C:\HumbleUI>git rev-parse HEAD
69faab0123f61c242e34061e8bcaaf772b46d0e1
```
```
C:\HumbleUI>python3.exe script\nrepl.py
nREPL server started on port 58078 on host 127.0.0.1 - nrepl://127.0.0.1:58078
nREPL 1.0.0
Clojure 1.11.1
Java HotSpot(TM) 64-Bit Server VM 19.0.1+10-21
Interrupt: Control+C
Exit:      Control+D or (exit) or (quit)
[ 33 ] LayerD3D12.cc:44 Failed to init DX12Device
io.github.humbleui.jwm.LayerNotSupportedException: Failed to init DX12 device
        at io.github.humbleui.jwm.LayerD3D12._nAttach(Native Method)
        at io.github.humbleui.jwm.LayerD3D12.attach(LayerD3D12.java:18)
        at io.github.humbleui.jwm.skija.LayerD3D12Skija.attach(LayerD3D12Skija.java:18)
        at io.github.humbleui.jwm.Window.setLayer(Window.java:64)
        at io.github.humbleui.window$make.invokeStatic(window.clj:114)
        at io.github.humbleui.window$make.invoke(window.clj:30)
        at io.github.humbleui.ui.window$window.invokeStatic(window.clj:42)
        at io.github.humbleui.ui.window$window.invoke(window.clj:9)
        at user$_main$fn__7914$fn__7915.invoke(user.clj:128)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.github.humbleui.jwm.App.lambda$start$1(App.java:35)
        at io.github.humbleui.jwm.App._nStart(Native Method)
        at io.github.humbleui.jwm.App.start(App.java:28)
        at io.github.humbleui.app$start.invokeStatic(app.clj:16)
        at io.github.humbleui.app$start.invoke(app.clj:15)
        at user$_main$fn__7914.invoke(user.clj:125)
        at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
user=>
```

**Comment by chrysophylax** [comment]
Are you running DirectX12?

**Comment by Dimagog** [comment]
Yes, and `dxdiag` finds no issues.

**Comment by tonsky** [comment]
I’d appreciate if you help us debug this issue. Code in question is here https://github.com/HumbleUI/JWM/blob/f270568ebd0ad2dee07b89eead76509997517448/windows/cc/D3D12/DX12Device.cc#L7-L42 and here https://github.com/HumbleUI/JWM/blob/main/windows/cc/D3D12/DX12Common.cc. I can help you with setting up compilation and answer any questions.

What graphics card do you have, btw?
