### ISSUE TITLE
`[first experience]` Exception in `start-app!`

### ISSUE THREAD

**Issue by harold** [HumbleUI/HumbleUI#64]
https://github.com/HumbleUI/HumbleUI/blob/69faab0123f61c242e34061e8bcaaf772b46d0e1/src/io/github/humbleui/ui/window.clj#L57

Hi! I appreciate this undertaking, it's impressive and an area in which I have an interest.

I was taken by the attractiveness of the simple example at the bottom of the readme:

https://github.com/HumbleUI/HumbleUI/blob/127b399c66db47cede838edeb9d56ad009ca6d5b/README.md?plain=1#L110-L122

I tried it myself, and encountered an exception:

```clojure
> (require '[io.github.humbleui.ui :as ui])
nil
> (def ui
   (ui/default-theme {}
     (ui/center
       (ui/label "Hello from Humble UI! 👋"))))
#'ui
> ui
#object[io.github.humbleui.ui.dynamic.Contextual 0x46742e8f "io.github.humbleui.ui.dynamic.Contextual@46742e8f"]
> (ui/start-app!
   (ui/window
     {:title "Humble 🐝 UI"}
     #'ui))
#<Future@6c73825a: :pending>java.lang.NullPointerException
	at clojure.lang.Numbers.ops(Numbers.java:1095)
	at clojure.lang.Numbers.minus(Numbers.java:164)
	at io.github.humbleui.ui.window$window.invokeStatic(window.clj:57)
	at io.github.humbleui.ui.window$window.invoke(window.clj:9)
	at eval38357$fn__38358$fn__38359.invoke(form-init6195262237181650313.clj:22)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.github.humbleui.jwm.App.lambda$start$1(App.java:35)
	at io.github.humbleui.jwm.App._nStart(Native Method)
	at io.github.humbleui.jwm.App.start(App.java:28)
	at io.github.humbleui.app$start.invokeStatic(app.clj:16)
	at io.github.humbleui.app$start.invoke(app.clj:15)
	at eval38357$fn__38358.invoke(form-init6195262237181650313.clj:21)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I'm sure I've screwed something up. Any thought on what it might be?

Thanks again for your time and consideration.

**Comment by harold** [comment]
@cnuernber - tangentially relevant to your interests.

**Comment by harold** [comment]
Interestingly, the ants (https://github.com/tonsky/humble-ants) demo works.

**Comment by Folcon** [comment]
@harold, do you have your code up anywhere? Also is this on macos? There are some minor os differences still being worked on, so it's worthwhile highlighting which you're using.

**Comment by harold** [comment]
> @harold, do you have your code up anywhere? Also is this on macos? There are some minor os differences still being worked on, so it's worthwhile highlighting which you're using.

Thanks for the reply.

I was doing this inside another project, but I can make a minimal example, which will be more helpful. Im away from the computer but I can do something later today.

I am on Linux, Ubuntu. But I also have i3 window manager. 

Glad to know this project is alive and I look forward to helping fix this bug.

**Comment by cnuernber** [comment]
It works for me given this deps.edn:

```clojure
{:paths ["src"]
 :deps {io.github.humbleui/humbleui {:git/url "https://github.com/HumbleUI/HumbleUI.git"
                                                 :sha "69faab0123f61c242e34061e8bcaaf772b46d0e1"}}}
```

**Comment by harold** [comment]
Great! Thanks @Folcon and @cnuernber ...

This was user error (a mistake on my part)

I was integrating this into a project that was dependent on an older version of `io.github.humbleui/types` (in particular, `0.1.1`) ... some judicious `lein deps :tree` and getting everything right with my `:exclusions` and `:classifier` and it's working now.

Hopefully I'll have more interesting questions soon. I super appreciate everyone's time and consideration.
