### ISSUE TITLE
UnsatisfiedLinkError: Library file skija.dll not found in windows if version difference

### ISSUE THREAD

**Issue by Folcon** [HumbleUI/HumbleUI#65]
This is a relatively minor issue, but I thought I should flag it, when `io.github.humbleui/skija-shared`'s library version is out of sync with `io.github.humbleui/skija-windows` as is the case right now with it being `0.109.1` vs `0.109.0`, we get the link error below:
```clojure
Exception in thread "main" Syntax error macroexpanding at (core.clj:33:3).
	at clojure.lang.Compiler$StaticMethodExpr.eval(Compiler.java:1750)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.eval(Compiler.java:7199)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at io.github.humbleui.window$eval1686$loading__6789__auto____1687.invoke(window.clj:1)
	at io.github.humbleui.window$eval1686.invokeStatic(window.clj:1)
	at io.github.humbleui.window$eval1686.invoke(window.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at user$eval138$loading__6789__auto____139.invoke(user.clj:1)
	at user$eval138.invokeStatic(user.clj:1)
	at user$eval138.invoke(user.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:368)
	at clojure.lang.RT.maybeLoadResourceScript(RT.java:364)
	at clojure.lang.RT.doInit(RT.java:486)
	at clojure.lang.RT.init(RT.java:467)
	at clojure.main.main(main.java:38)
Caused by: java.lang.UnsatisfiedLinkError: Library file skija.dll not found in io/github/humbleui/skija/windows/x64/
	at io.github.humbleui.skija.impl.Library._extract(Library.java:160)
	at io.github.humbleui.skija.impl.Library.load(Library.java:101)
	at io.github.humbleui.skija.impl.Library.staticLoad(Library.java:20)
	at io.github.humbleui.skija.shaper.Shaper.<clinit>(Shaper.java:14)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
	at clojure.lang.Compiler$StaticMethodExpr.eval(Compiler.java:1743)
	... 65 more
```

The obvious workaround is to downgrade `io.github.humbleui/skija-shared` to match window's when working in windows, just wondering if there's a more elegant way to handle this?

**Comment by tonsky** [comment]
Sorry, what do you mean by “out of sync”? Is it out of sync somewhere in public repo, or do you make it out of sync intentionally? As far as I can see, e.g. skija-macos-arm64-0.109.1 depends on skija-shared-0.109.1, which is in sync?

**Comment by Folcon** [comment]
Sorry, I mean out of sync as in `io.github.humbleui/skija-windows` is on version number `0.109.0`, whereas `io.github.humbleui/skija-shared` is on `0.109.1`.

From what I've seen doing this in deps fails on windows as it can't find the dll:
```
[io.github.humbleui/skija-shared "0.109.1"]
[io.github.humbleui/skija-windows "0.109.0"]
[io.github.humbleui/skija-linux "0.109.0"]
[io.github.humbleui/skija-macos-x64 "0.109.1"]
[io.github.humbleui/skija-macos-arm64 "0.109.1"]
```
It may be pretty non-obvious to a user that updating to the latest libs on linux or windows in the current state can cause the app to fail to launch and what they need to do is downgrade `skija-shared` to `0.109.0`.
Perhaps this is a leiningen specific issue, which I only just considered, in which case, it's less of a problem =)...

**Comment by tonsky** [comment]
Yeah, don’t do that :) Actually, you don’t need to specify skija-shared at all, since it’s included as a transitive dependency in platform ones. And you should switch to skija-windows-x64/skija-linux-x64, they changed the name in 0.109.1

**Comment by Folcon** [comment]
Ah cool, thanks.
